services:
  next:
    build:
      context: .
      target: next
    ports:
      - "3000:3000"

    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app #map . local vers /app du docker
    

    
